name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Caches 'vendor/bundle' automatically

      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Run RuboCop
      - name: Run RuboCop
        run: bundle exec rubocop
